name: Build BigSurface
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Kext
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Foarte important pentru VoodooSerial/Lilu

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build Kext
        # Am adăugat calea corectă către proiect: BigSurface/BigSurface.xcodeproj
        run: |
          xcodebuild -project BigSurface/BigSurface.xcodeproj -scheme BigSurface -configuration Release ARCHS="x86_64" CODE_SIGNING_ALLOWED=NO

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BigSurface-Kext-SL4
          # Verificăm unde Xcode pune fișierul (uzual în folderul proiectului)
          path: BigSurface/build/Release/BigSurface.kext
